rg-96: min password length
BinaryStudioAcademy/bsa-winter-2023-2024-resumegemm pull request #105
Opened 2024-02-29 22:59 UTC by ValentinaTenus

2024-03-04 18:40 UTC, honkster-nazarii requested changes

2024-03-04 19:05 UTC, ValentinaTenus commented on shared/src/bundles/users/enums/user-validation-message.enum.ts
> +    PASSWORD_INVALID = 'Invalid password.\nUse 8-64 characters, mix uppercase, lowercase, numbers, and special characters. No spaces allowed',
Yes, I also wanted make it shorter  but it must be like this((

2024-03-04 19:06 UTC, ValentinaTenus commented on shared/src/bundles/users/enums/user-validation-message.enum.ts
> +    PASSWORD_INVALID = 'Invalid password.\nUse 8-64 characters, mix uppercase, lowercase, numbers, and special characters. No spaces allowed',
and styles are alredy changed for this error. It just need to be merged

2024-03-04 19:07 UTC, ValentinaTenus commented on frontend/src/bundles/auth/components/sign-up-form/validation/sign-up-validation.ts
> +    password: joi.string().trim().min(8).regex(/^\S*$/).required().messages({
because it includes 8 symbols. What's wrong?

2024-03-04 19:08 UTC, honkster-nazarii commented on frontend/src/bundles/auth/components/sign-up-form/validation/sign-up-validation.ts
> +    password: joi.string().trim().min(8).regex(/^\S*$/).required().messages({
it has trailing spaces

2024-03-04 19:12 UTC, honkster-nazarii commented on frontend/src/bundles/auth/components/sign-up-form/validation/sign-up-validation.ts
> +    password: joi.string().trim().min(8).regex(/^\S*$/).required().messages({
and if you hide the symbols, it will show that password is like 20 symbols long

2024-03-04 19:21 UTC, Vitaliy-Kalenichenko commented
Conflicts:(

2024-03-04 19:41 UTC, ValentinaTenus commented on frontend/src/bundles/auth/components/sign-up-form/validation/sign-up-validation.ts
> +    password: joi.string().trim().min(8).regex(/^\S*$/).required().messages({
yes, I know. I've fixed it in another PR because it was separate bug))I've remove trim here as well

2024-03-06 10:45 UTC, Vitaliy-Kalenichenko approved these changes

2024-03-06 10:45 UTC, merged