rg-85: Added subscriptions notifications.
BinaryStudioAcademy/bsa-winter-2023-2024-resumegemm pull request #126
Opened 2024-03-03 12:11 UTC by jurok3x

* Added email notifications on subscription.
![email](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-resumegemm/assets/78302126/18be678f-90ce-43f2-8d16-21bc16d3907e)

2024-03-05 12:00 UTC, RevolveStrm approved these changes

2024-03-06 16:41 UTC, MaxPoplavskiy requested changes

2024-03-06 16:41 UTC, MaxPoplavskiy commented on backend/src/bundles/stripe-events/helpers/subscription-email-generator.ts
> +    subject = 'Subscription',
consider using an enum

2024-03-06 16:41 UTC, MaxPoplavskiy commented on backend/src/bundles/stripe-events/helpers/subscription-email-generator.ts
> +        current_period_start * 1000,
consider moving 1000 to a constant

2024-03-06 16:41 UTC, MaxPoplavskiy commented on backend/src/bundles/stripe-events/helpers/subscription-email-generator.ts
> +    const endDate = new Date(current_period_end * 1000).toLocaleDateString();
consider moving 1000 to a constant

2024-03-07 11:59 UTC, jurok3x commented on backend/src/bundles/stripe-events/helpers/subscription-email-generator.ts
> +    subject = 'Subscription',
done

2024-03-07 11:59 UTC, jurok3x commented on backend/src/bundles/stripe-events/helpers/subscription-email-generator.ts
> +    const endDate = new Date(current_period_end * 1000).toLocaleDateString();
done

2024-03-07 12:06 UTC, jurok3x commented on backend/src/bundles/stripe-events/helpers/subscription-email-generator.ts
> +        current_period_start * 1000,
done

2024-03-07 16:22 UTC, Icerock10 approved these changes

2024-03-11 12:38 UTC, Icerock10 commented on backend/src/bundles/stripe-events/helpers/subscription-email-generator.ts
> +        const regex = new RegExp(`{${key}}`, 'g');
https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-resumegemm/pull/174

2024-03-11 13:06 UTC, jurok3x commented
@Vitaliy-Kalenichenko suggest close this PR, since [#174](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-resumegemm/pull/174)  contains all changes and much more.

2024-03-12 17:07 UTC, closed without merging