rg-83: Add Subscription Plans / Connect To Stripe Actions
BinaryStudioAcademy/bsa-winter-2023-2024-resumegemm pull request #129
Opened 2024-03-03 18:53 UTC by RevolveStrm

![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-resumegemm/assets/60217935/dd4f8c69-f2a4-421e-a92c-f62840de6572)
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-resumegemm/assets/60217935/6c880d26-4374-47b5-8502-5a9721aa5d78)
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-resumegemm/assets/60217935/6f3c5d1c-dc5b-4366-95a1-14f8212ce0fd)
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-resumegemm/assets/60217935/6f69929a-a2d8-45a0-8d1e-c675cab046a7)

2024-03-04 13:33 UTC, jurok3x requested changes

2024-03-04 13:33 UTC, jurok3x commented on backend/src/common/server-application/server-app.ts
> +    preParsing as preParsingPlugin
Fix imports please.

2024-03-04 16:23 UTC, RevolveStrm commented on backend/src/common/plugins/preparsing/preparsing-plugin.ts
> +                });
Using Readable.from() is a great advice!

2024-03-04 16:24 UTC, RevolveStrm commented on backend/src/common/server-application/server-app.ts
> +    preParsing as preParsingPlugin
I will fix these imports!

2024-03-05 09:41 UTC, Vitaliy-Kalenichenko approved these changes

2024-03-05 09:41 UTC, merged