rg-129: Update Profile Data
BinaryStudioAcademy/bsa-winter-2023-2024-resumegemm pull request #153
Opened 2024-03-05 19:17 UTC by Valentyn13

2024-03-05 19:35 UTC, Valentyn13 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Save / update data on profile page](https://trello.com/c/LsZwJoxX/129-save-update-data-on-profile-page)

2024-03-07 15:39 UTC, Icerock10 requested changes

2024-03-07 15:39 UTC, Icerock10 commented on backend/src/bundles/profile/profile.repository.ts
> +    }
since we are extending the AbstractRepo, find a way to reuse this method for both userRepo and profileRepo

2024-03-07 15:39 UTC, Icerock10 commented on backend/src/bundles/users/user.service.ts
>                      'createdAt' | 'updatedAt' | 'id'
Please, refactor types, there is a better way to do so

2024-03-07 15:52 UTC, Icerock10 requested changes

2024-03-07 15:52 UTC, Icerock10 commented on frontend/src/bundles/auth/store/slice.ts
> +            action: PayloadAction<UserWithProfileRelationAndOauthConnections>,
this type `UserWithProfileRelationAndOauthConnections`, should be non-actual after you resolve conflicts

Why did you add setUser?

2024-03-07 15:52 UTC, Icerock10 commented on frontend/src/bundles/profile/store/actions.ts
>  /* eslint-disable @typescript-eslint/no-invalid-void-type */
I've fixed that in my branch, you can checkout this file

2024-03-08 21:05 UTC, closed without merging