rg-162: Add Error Logging To STDERR
BinaryStudioAcademy/bsa-winter-2023-2024-resumegemm pull request #166
Opened 2024-03-06 18:15 UTC by RevolveStrm

Added a new error logger which redirects errors to stderr

2024-03-06 18:26 UTC, Valentyn13 approved these changes

2024-03-06 18:48 UTC, MaxPoplavskiy requested changes

2024-03-06 18:48 UTC, MaxPoplavskiy commented on package-lock.json
No packages were added, so this file should not be changed

2024-03-06 21:10 UTC, MaxPoplavskiy approved these changes

2024-03-07 13:03 UTC, jurok3x approved these changes

2024-03-07 22:58 UTC, apofis96 approved these changes

2024-03-07 22:58 UTC, merged