rg-155: Fix add error message
BinaryStudioAcademy/bsa-winter-2023-2024-resumegemm pull request #168
Opened 2024-03-06 21:59 UTC by Icerock10

![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-resumegemm/assets/24661681/82ea5b85-385b-4558-9b20-ffeafbd20e0b)

2024-03-06 22:26 UTC, ValentinaTenus commented
the same as https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-resumegemm/pull/169

2024-03-06 23:19 UTC, siefimov approved these changes

2024-03-07 06:44 UTC, MaxPoplavskiy approved these changes

2024-03-07 07:09 UTC, Valentyn13 approved these changes

2024-03-07 12:02 UTC, MaxPoplavskiy approved these changes

2024-03-07 12:07 UTC, ValentinaTenus approved these changes

2024-03-08 09:23 UTC, Vitaliy-Kalenichenko commented
Conflicts :(

2024-03-11 17:33 UTC, MaxPoplavskiy approved these changes

2024-03-13 09:51 UTC, Vitaliy-Kalenichenko requested changes

2024-03-13 09:51 UTC, Vitaliy-Kalenichenko commented on frontend/src/bundles/common/hooks/use-form-error/use-form-error.hook.ts
> +            const fieldName = errorType as keyof UserSignInRequestDto;
It looks like general hook. Why UserSignInRequestDto type is used?

2024-03-14 08:36 UTC, Valentyn13 approved these changes

2024-03-14 11:45 UTC, ValentinaTenus approved these changes

2024-03-14 17:25 UTC, Vitaliy-Kalenichenko approved these changes

2024-03-14 17:25 UTC, merged