rg-151: User avatar upload
BinaryStudioAcademy/bsa-winter-2023-2024-resumegemm pull request #187
Opened 2024-03-08 14:13 UTC by vlad-blip

2024-03-08 14:38 UTC, MaxPoplavskiy approved these changes

2024-03-08 19:21 UTC, honkster-nazarii requested changes
Would be cool to have a short demo

2024-03-08 19:21 UTC, honkster-nazarii commented on backend/src/bundles/profile/profile.repository.ts
> +    public async uploadAvatar({
confusing name for repository method, consider changing it to more fitting name

2024-03-08 19:44 UTC, vlad-blip commented
> Would be cool to have a short demo

Do you mean a video demo? Gonna add it tomorrow.

2024-03-08 20:03 UTC, Icerock10 approved these changes

2024-03-08 20:05 UTC, honkster-nazarii approved these changes

2024-03-11 19:27 UTC, Icerock10 commented
conflicts

2024-03-12 14:38 UTC, MaxPoplavskiy approved these changes

2024-03-13 22:41 UTC, honkster-nazarii approved these changes

2024-03-14 18:07 UTC, Vitaliy-Kalenichenko approved these changes

2024-03-14 18:07 UTC, merged