rg-12: Add user flow steps logic
BinaryStudioAcademy/bsa-winter-2023-2024-resumegemm pull request #2
Opened 2024-02-11 16:01 UTC by MariaPetrukhnova

I create logic which allow to switch between tabs with click on Next and also with click on tabs. Hope, it is correct. If no - I'll remove tab clicks. Also I didn't found what to do on the last step with the Next button. Should it become a Save button - or how it should finish the data saving?

Not very confident with folders structure... I save it in separate bundle, but tbd...

2024-02-12 18:51 UTC, apofis96 requested changes

2024-02-12 18:51 UTC, apofis96 commented on frontend/src/bundles/cv-editor/components/user-flow-bar/user-flow-bar.module.css
> +.userFlow {
use scss

2024-02-12 21:27 UTC, Vitaliy-Kalenichenko commented on frontend/src/bundles/cv-editor/components/user-flow-bar/user-flow-bar.tsx
> +            <aside className={css.userFlow__sidebar}>
Section and Aside are interchangeable tags, and none of them should be used in this component

2024-02-12 21:30 UTC, Vitaliy-Kalenichenko commented on frontend/src/bundles/cv-editor/components/user-flow-bar/user-flow-bar.tsx
> +const UserFlow: React.FC = () => {
This component is too specific, try to make it more generic

2024-02-12 21:31 UTC, Vitaliy-Kalenichenko commented on frontend/src/bundles/cv-editor/components/user-flow-bar/user-flow-bar.tsx
> +                        return (
Don't use `return` key-word in layout

2024-02-12 21:32 UTC, Vitaliy-Kalenichenko commented on frontend/src/bundles/cv-editor/components/user-flow-bar/user-flow-bar.tsx
> +                        <button type='button' onClick={onTabClick(`${key}`)}
Consider using NavLink here

2024-02-12 21:37 UTC, Vitaliy-Kalenichenko commented on frontend/src/bundles/cv-editor/components/user-flow-bar/types/interface.ts
> +const UserFlowBtns: Map = {
Try to find better locations for this `const`. It is should be in `types/interface.ts`?

2024-02-12 21:38 UTC, Vitaliy-Kalenichenko commented on frontend/src/bundles/cv-editor/components/user-flow-bar/user-flow-bar.tsx
> +        //add logic to save fullfilled data and to connect it with progress bar
Progress bar should not depend on this component

2024-02-13 21:36 UTC, Vitaliy-Kalenichenko commented on frontend/src/bundles/cv-editor/components/online-editor/online-editor-handler.tsx
> +    const [activeTab, setActiveTab] = useState(0);
Judging by variables names, I would expect to have a tab object here. 
Consider using `activeTabIndex` name

2024-02-13 21:38 UTC, Vitaliy-Kalenichenko commented on frontend/src/bundles/cv-editor/components/online-editor/online-editor-handler.tsx
> +        setActiveTab(activeTab < tabs.length - 1 ? activeTab + 1 : activeTab);
Use callback here to prevent getting old value, like: setActiveTab(prevActiveTabIndex => prevActiveTabIndex <.....

2024-02-13 21:43 UTC, Vitaliy-Kalenichenko commented on frontend/src/bundles/cv-editor/components/online-editor/online-editor-handler.tsx
> +                        <li key={tab.id}>
Consider using label instead of id

2024-02-14 18:50 UTC, apofis96 requested changes

2024-02-14 18:50 UTC, apofis96 commented on frontend/src/bundles/cv-editor/components/online-editor/online-editor-handler.tsx
> +import css from './online-editor-handler.module.scss';
```suggestion
import styles from './online-editor-handler.module.scss';
```

2024-02-14 20:37 UTC, Vitaliy-Kalenichenko commented
Resolve conflicts

2024-02-16 11:14 UTC, Vitaliy-Kalenichenko approved these changes

2024-02-16 11:15 UTC, merged