Task/rg 7 sign forms
BinaryStudioAcademy/bsa-winter-2023-2024-resumegemm pull request #20
Opened 2024-02-14 10:20 UTC by ValentinaTenus

![logIn-large](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-resumegemm/assets/120641395/ee8025e7-041b-4261-b33e-3a4ce90ec28a)
![sign-page-large](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-resumegemm/assets/120641395/6ef4bf76-b6fe-44b8-9f08-bfa528c0e834)
![logIn-small](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-resumegemm/assets/120641395/c11aa92e-3566-4c40-be3f-445d05ffa2e8)
![signUp-small](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-resumegemm/assets/120641395/81ad42aa-6342-402f-a8c2-41eaa2f80462)

2024-02-14 21:24 UTC, Vitaliy-Kalenichenko commented
Resolve merge conflicts

2024-02-17 02:13 UTC, ValentinaTenus commented
i've made some changes in input component. i've added type as props and and made pull request. I need mail and password type for forms

2024-02-20 22:15 UTC, Vitaliy-Kalenichenko commented
Resolve conflicts

2024-02-20 22:22 UTC, Vitaliy-Kalenichenko requested changes

2024-02-21 09:02 UTC, Vitaliy-Kalenichenko approved these changes

2024-02-21 09:02 UTC, merged