rg-206: Add Header To Template Editor
BinaryStudioAcademy/bsa-winter-2023-2024-resumegemm pull request #213
Opened 2024-03-13 07:44 UTC by Valentyn13

2024-03-13 17:25 UTC, Valentyn13 commented
![](https://github.trello.services/images/mini-trello-icon.png) [The header is missing on the "Template editor" page.](https://trello.com/c/lP2anwBX/206-the-header-is-missing-on-the-template-editor-page)

2024-03-13 21:25 UTC, siefimov approved these changes

2024-03-13 22:38 UTC, honkster-nazarii approved these changes

2024-03-14 09:10 UTC, Vitaliy-Kalenichenko commented on frontend/src/bundles/edit-template/edit-template.tsx
> +                                style={{ 'display': 'flex' }}
You can add it to class

2024-03-14 09:59 UTC, Valentyn13 commented on frontend/src/bundles/edit-template/edit-template.tsx
> +                                style={{ 'display': 'flex' }}
done

2024-03-14 18:02 UTC, Vitaliy-Kalenichenko requested changes
https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-resumegemm/pull/217/files#r1525249028

2024-03-20 10:56 UTC, closed without merging