rg-220: template customize
BinaryStudioAcademy/bsa-winter-2023-2024-resumegemm pull request #232
Opened 2024-03-14 19:19 UTC by MaxPoplavskiy

![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-resumegemm/assets/92567020/a8cf5db0-9a18-4955-8dc3-c379a05d2b03)

![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-resumegemm/assets/92567020/808a93bd-9ecc-4939-a455-a33dff86c414)

![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-resumegemm/assets/92567020/5dfe6397-6d73-4a9b-84f3-538d4850d9c6)

2024-03-14 20:50 UTC, honkster-nazarii requested changes

2024-03-14 20:50 UTC, honkster-nazarii commented on frontend/src/bundles/edit-template/edit-template.tsx
> +const dropdownOptions = [
can be moved to a separate file

2024-03-14 20:51 UTC, honkster-nazarii commented
add scrolling for right panel

2024-03-15 10:41 UTC, Valentyn13 approved these changes

2024-03-15 11:48 UTC, jurok3x approved these changes

2024-03-15 12:23 UTC, RevolveStrm approved these changes

2024-03-18 10:24 UTC, siefimov commented
Conflicts.

2024-03-18 10:25 UTC, siefimov reviewed
Conflicts.

2024-03-18 12:23 UTC, honkster-nazarii approved these changes

2024-03-18 15:05 UTC, MaxPoplavskiy commented
![](https://github.trello.services/images/mini-trello-icon.png) [Template customize](https://trello.com/c/f3IsPTG8/220-template-customize)

2024-03-21 08:16 UTC, Icerock10 approved these changes

2024-03-21 08:17 UTC, merged