rg-133: replace templates
BinaryStudioAcademy/bsa-winter-2023-2024-resumegemm pull request #235
Opened 2024-03-15 00:29 UTC by ValentinaTenus

2024-03-15 10:39 UTC, Valentyn13 approved these changes

2024-03-15 12:39 UTC, MaxPoplavskiy approved these changes

2024-03-15 13:24 UTC, honkster-nazarii approved these changes

2024-03-18 12:16 UTC, MaxPoplavskiy commented
Conflicts

2024-03-19 07:57 UTC, Icerock10 requested changes
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-resumegemm/assets/24661681/85bf6dc9-2e0a-41d9-a327-5957bea35837)

Are you sure you passing the limit correctly?

2024-03-19 16:23 UTC, vlad-blip commented
![](https://github.trello.services/images/mini-trello-icon.png) [replace templates in home page with recently viewed templates](https://trello.com/c/l2udzVbe/133-replace-templates-in-home-page-with-recently-viewed-templates)

2024-03-21 12:01 UTC, closed without merging