rg-230: + added template seed data
BinaryStudioAcademy/bsa-winter-2023-2024-resumegemm pull request #243
Opened 2024-03-15 14:58 UTC by vlad-blip

![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-resumegemm/assets/70428008/4c27bf14-35c9-4830-b37f-28314dc9ffa7)

2024-03-15 14:59 UTC, vlad-blip commented
![](https://github.trello.services/images/mini-trello-icon.png) [Make template seeds meaningful](https://trello.com/c/XzWyb02s/230-make-template-seeds-meaningful)

2024-03-15 15:09 UTC, MaxPoplavskiy approved these changes

2024-03-15 15:26 UTC, honkster-nazarii approved these changes

2024-03-18 09:44 UTC, Icerock10 commented
conflicts

2024-03-18 09:45 UTC, Icerock10 requested changes
conflicts

2024-03-20 10:51 UTC, Icerock10 approved these changes

2024-03-20 10:52 UTC, merged