rg-221: Add restrictions without subscription
BinaryStudioAcademy/bsa-winter-2023-2024-resumegemm pull request #254
Opened 2024-03-17 22:33 UTC by siefimov

Added restriction for free subscription users:

- to create more than 1 resume, 
- to download more than 1 resume in PDF format.

![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-resumegemm/assets/17623764/332ee821-28df-43ba-b7f3-096a7c6e44c0)

![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-resumegemm/assets/17623764/f19c6d1a-3502-43c3-ab6a-e008fb526013)

2024-03-18 14:27 UTC, ValentinaTenus commented on frontend/src/bundles/resume/pages/resume-page.tsx
> +                            // onClick={createResumeAccessLink}
don't leave comment

2024-03-18 14:37 UTC, ValentinaTenus commented on frontend/src/index.tsx
> +                                            element: 'EditResume',
is it correct?

2024-03-18 14:37 UTC, ValentinaTenus commented on shared/src/bundles/resumes/types/resume-views-count-response-dto.type.ts
> +    updatedAt: string | undefined;
```suggestion
    updatedAt?: string;
```

2024-03-19 19:35 UTC, siefimov commented on frontend/src/bundles/resume/pages/resume-page.tsx
> +                            // onClick={createResumeAccessLink}
Done.

2024-03-19 19:36 UTC, siefimov commented on frontend/src/index.tsx
> +                                            element: 'EditResume',
It's just for testing purpose.

2024-03-19 23:03 UTC, siefimov commented on frontend/src/index.tsx
> +                                            element: 'EditResume',
Already changed to real component.

2024-03-20 07:53 UTC, vlad-blip commented
![](https://github.trello.services/images/mini-trello-icon.png) [Restrictions without subscription](https://trello.com/c/km3877Sh/221-restrictions-without-subscription)

2024-03-20 07:54 UTC, vlad-blip approved these changes

2024-03-20 10:26 UTC, Valentyn13 commented
conflicts again :(

2024-03-20 23:32 UTC, Icerock10 requested changes
conflicts

2024-03-21 10:41 UTC, closed without merging