rg-253: * move header to ResumesHeader
BinaryStudioAcademy/bsa-winter-2023-2024-resumegemm pull request #264
Opened 2024-03-19 11:16 UTC by MaxPoplavskiy

2024-03-19 11:18 UTC, MaxPoplavskiy commented
![](https://github.trello.services/images/mini-trello-icon.png) [Move resume header to HeaderWrapper and remove AvatarHeader from resumes pages](https://trello.com/c/NUy17F3l/253-move-resume-header-to-headerwrapper-and-remove-avatarheader-from-resumes-pages)

2024-03-19 11:48 UTC, Valentyn13 approved these changes

2024-03-19 11:56 UTC, vlad-blip requested changes
Where did `Share resume button` go?🤔

2024-03-19 12:04 UTC, vlad-blip commented on frontend/src/bundles/common/components/header-wrapper/components/resumes-header/styles.module.scss
> +}
```suggestion
.share__icon {
    width: 25px;
    height: 25px;
    background-color: var(--color-black);
}
```

2024-03-19 14:38 UTC, ValentinaTenus commented on frontend/src/bundles/common/components/header-wrapper/components/resumes-header/resumes-header.tsx
> +import shareIcon from '~/assets/img/share-icon.svg';
consider import svg as react component
```suggestion
import ShareIcon from '~/assets/img/share-icon.svg?react';
```

2024-03-19 14:39 UTC, ValentinaTenus commented on frontend/src/bundles/common/components/header-wrapper/components/resumes-header/resumes-header.tsx
> +                    ></div>
```suggestion
                    <div className={styles.share__icon}
                        <ShareIcon />
                    </div>
```

2024-03-19 15:39 UTC, MaxPoplavskiy commented on frontend/src/bundles/common/components/header-wrapper/components/resumes-header/resumes-header.tsx
> +                    ></div>
Done

2024-03-19 15:39 UTC, MaxPoplavskiy commented on frontend/src/bundles/common/components/header-wrapper/components/resumes-header/resumes-header.tsx
> +import shareIcon from '~/assets/img/share-icon.svg';
Done

2024-03-19 18:06 UTC, vlad-blip approved these changes

2024-03-20 06:34 UTC, Icerock10 commented on frontend/src/bundles/common/components/header-wrapper/components/resumes-header/resumes-header.tsx
> +import { Header, RegularButton } from '../../../components';
```suggestion
import { Header, RegularButton } from '~';
```

2024-03-20 06:35 UTC, merged