rg-242: add sort functionality
BinaryStudioAcademy/bsa-winter-2023-2024-resumegemm pull request #267
Opened 2024-03-19 14:26 UTC by ValentinaTenus

2024-03-19 14:29 UTC, ValentinaTenus commented
https://trello.com/c/MrS5Ntln/242-the-sort-button-is-unresponsive-on-the-home-templates-page

2024-03-19 16:17 UTC, jurok3x requested changes

2024-03-19 21:25 UTC, ValentinaTenus commented
![](https://github.trello.services/images/mini-trello-icon.png) [The "Sort" button is unresponsive on the "Home/Templates" page.](https://trello.com/c/MrS5Ntln/242-the-sort-button-is-unresponsive-on-the-home-templates-page)

2024-03-20 10:10 UTC, vlad-blip approved these changes

2024-03-20 10:24 UTC, Valentyn13 approved these changes

2024-03-20 11:30 UTC, jurok3x approved these changes

2024-03-20 12:20 UTC, merged