rg-14: Add Resume Preview Layout
BinaryStudioAcademy/bsa-winter-2023-2024-resumegemm pull request #28
Opened 2024-02-15 10:56 UTC by siefimov

![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-resumegemm/assets/17623764/4491c5d2-74f1-4b55-a091-49408cbf3716)

2024-02-15 17:56 UTC, nickolay-grechkin requested changes

2024-02-15 17:56 UTC, nickolay-grechkin commented on frontend/src/bundles/resume-preview/components/common/badge/badge.tsx
> +const Badge: React.FC<BadgeProperties> = ({ title, className }) => (
Set default value for the className

2024-02-15 17:56 UTC, nickolay-grechkin commented on frontend/src/bundles/resume-preview/components/common/description-item/description-item.tsx
> +    className,
Set default value for the all className props

2024-02-15 17:56 UTC, nickolay-grechkin commented on frontend/src/bundles/resume-preview/components/contacts/contacts.tsx
> +                        href={`https://:${portfolio_url}`}
I think this can be moved to a const

2024-02-15 17:56 UTC, nickolay-grechkin commented on frontend/src/bundles/resume-preview/components/common/description-item/description-item.tsx
> +interface DescriptionItemProperties {
Change it's name to just Properties in all places and use type instead of interface.

2024-02-15 17:56 UTC, nickolay-grechkin commented on frontend/src/bundles/resume-preview/components/experience/components/experience-item/experience-item.tsx
> +                            ></span>
```suggestion
<span className={styles.experience__dot_devider} />
```

2024-02-15 17:56 UTC, nickolay-grechkin commented on frontend/src/bundles/resume-preview/components/experience/helpers/format-date.ts
> +const formatDate = (date: Data): string => {
```suggestion
const formatDate = (date: string): string => {
```

2024-02-15 17:56 UTC, nickolay-grechkin commented on frontend/src/bundles/resume-preview/components/recommendations/components/recommendation-item/recommendation-item.tsx
> +    item: {
I think this can be moved to separate type

2024-02-15 17:56 UTC, nickolay-grechkin commented on frontend/src/bundles/resume-preview/components/resume-preview/resume-review.tsx
> +                        json_styles={{
I think we should come up with the different approach to pass json_styles to component, current is hard to read.
Maybe create a separate function that will map json_styles.

2024-02-15 17:56 UTC, nickolay-grechkin commented on frontend/src/bundles/resume-preview/types/education-styles.type.ts
> +        color: string;
Can be moved to separate type and reused

2024-02-15 17:56 UTC, nickolay-grechkin commented on frontend/src/bundles/resume-preview/types/experience-styles.type.ts
> +        fontWeight: string;
Can be moved to separate type and reused

2024-02-16 07:58 UTC, Vitaliy-Kalenichenko commented on frontend/src/bundles/resume-preview/components/common/badge/badge.tsx
> +    <div className={`${styles.badge} ${className}`}>{title}</div>
Use cslx function to concatenate class names

2024-02-16 15:10 UTC, siefimov commented
I have made all the requested changes. please review my pull request again.

2024-02-19 09:27 UTC, Vitaliy-Kalenichenko commented on frontend/src/bundles/resume-preview/components/experience/components/experience-item/experience-item.tsx
> +                        company_logo.length > 0
It would be better to move this logic out of layout

2024-02-19 09:30 UTC, Vitaliy-Kalenichenko approved these changes

2024-02-19 09:30 UTC, Vitaliy-Kalenichenko commented
Resolve conflicts

2024-02-19 11:03 UTC, siefimov commented
Conflicts resolved.

2024-02-19 15:48 UTC, siefimov commented
One more approval is required!

2024-02-19 16:58 UTC, nickolay-grechkin approved these changes

2024-02-19 16:58 UTC, nickolay-grechkin commented
Resolve another conflicts 😢

2024-02-19 20:05 UTC, siefimov commented
Everything is green!)

2024-02-19 21:10 UTC, merged