rg-35: add 404 page. Dependency: rg-3
BinaryStudioAcademy/bsa-winter-2023-2024-resumegemm pull request #31
Opened 2024-02-15 16:30 UTC by MaxPoplavskiy

Create 404 page:
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-resumegemm/assets/92567020/2cea368a-8b64-4d76-84f7-dc015709326e)

2024-02-15 17:11 UTC, nickolay-grechkin commented
As I understand it correctly, you created your branch from [this one](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-resumegemm/pull/5/files). In that case, you need to create a merge request not to the dev branch, but to the branch from which you created yours. Your pull request will be merged after the original one, and reviewers won't need to check the same changes twice. And also resolve conflicts, please.

2024-02-15 17:12 UTC, nickolay-grechkin requested changes
As I understand it correctly, you created your branch from [this one](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-resumegemm/pull/5/files). In that case, you need to create a merge request not to the dev branch, but to the branch from which you created yours. Your pull request will be merged after the original one, and reviewers won't need to check the same changes twice. And also resolve conflicts, please.

2024-02-15 18:15 UTC, Vitaliy-Kalenichenko approved these changes

2024-02-15 20:30 UTC, Vitaliy-Kalenichenko commented on frontend/src/app/app.tsx
> +                    <Link to={AppRoute.SIGN_UP}>Sign up</Link>11
Looks like this change is redundant

2024-02-16 06:19 UTC, MaxPoplavskiy commented on frontend/src/app/app.tsx
> +                    <Link to={AppRoute.SIGN_UP}>Sign up</Link>11
Done. Remove redundant text in app

2024-02-18 20:37 UTC, apofis96 approved these changes

2024-02-19 16:51 UTC, merged