rg-36: Add Toaster
BinaryStudioAcademy/bsa-winter-2023-2024-resumegemm pull request #34
Opened 2024-02-16 09:44 UTC by RevolveStrm

Added notifications library [react-toastify](https://www.npmjs.com/package/react-toastify).

2024-02-18 20:39 UTC, apofis96 requested changes
Add use example

2024-02-20 22:05 UTC, Vitaliy-Kalenichenko requested changes
Don't use library components directly. Wrap them in their own component
We discussed that to display a toast you need to use either context or redux

2024-02-23 06:22 UTC, RevolveStrm commented
Wrapped the toaster in context

![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-resumegemm/assets/60217935/0a5c3a50-d5fc-4f37-8b69-4641855fae46)

Sorry, I accidentally pushed all the commits) How can this be prevented in the future?

2024-02-25 18:30 UTC, apofis96 approved these changes

2024-02-25 22:02 UTC, Vitaliy-Kalenichenko approved these changes

2024-02-25 22:02 UTC, merged