rg-33: Images CRUD
BinaryStudioAcademy/bsa-winter-2023-2024-resumegemm pull request #44
Opened 2024-02-19 14:39 UTC by vlad-blip

2024-02-19 17:56 UTC, nickolay-grechkin approved these changes

2024-02-20 15:28 UTC, Vitaliy-Kalenichenko commented on backend/src/bundles/profile/profile.repository.ts
> +        return await this.profileModel
Why is the `await` added here?

2024-02-20 15:31 UTC, Vitaliy-Kalenichenko requested changes
It's backend related task, so there should not be any changes in the frontend folder

2024-02-20 15:33 UTC, Vitaliy-Kalenichenko commented
Consider limiting the file size. Perhaps 10 MB will be enough.

2024-02-20 15:38 UTC, vlad-blip commented on backend/src/bundles/profile/profile.repository.ts
> +        return await this.profileModel
because typescript told me so

2024-02-20 15:57 UTC, vlad-blip commented
> It's backend related task, so there should not be any changes in the frontend folder

I haven't made any significant changes to frontend folder. I just ran `npm run prettify` command to fix all styling issues, because lint wouldn't let me commit anything while having file styling errors, and deleted the export duplicates. I didn't touch any logic on frontend.

2024-02-20 21:46 UTC, Vitaliy-Kalenichenko commented
Please revert the commit in which you ran `npm run prettify`. And don't do it again. If you need to run linters ask about a task for it

2024-02-21 19:00 UTC, closed without merging