rg-47: Update refresh token logic
BinaryStudioAcademy/bsa-winter-2023-2024-resumegemm pull request #49
Opened 2024-02-19 22:57 UTC by Icerock10

2024-02-20 08:56 UTC, Vitaliy-Kalenichenko commented on backend/src/common/config/config.package.ts
>                  REFRESH_TOKEN_EXPIRES_IN: '30d',
Make sure that the cookie's lifetime expires at the same time as the refresh token's lifetime

2024-02-20 09:38 UTC, Vitaliy-Kalenichenko requested changes
Cookie signature - looks like it should be unique for each user
It's better to hardcode all expires_in values

2024-02-20 22:31 UTC, Vitaliy-Kalenichenko approved these changes

2024-02-20 23:07 UTC, honkster-nazarii commented
Is it really neccesary to update refresh token after `regenerateToken`?

2024-02-21 08:54 UTC, Vitaliy-Kalenichenko commented
> Is it really neccesary to update refresh token after `regenerateToken`?

Are there any reasons not to do that?

2024-02-21 21:17 UTC, closed without merging