rg-33: Images CRUD to development
BinaryStudioAcademy/bsa-winter-2023-2024-resumegemm pull request #55
Opened 2024-02-21 18:58 UTC by vlad-blip

Copy of #44 with minor changes.

2024-02-26 16:47 UTC, nickolay-grechkin approved these changes

2024-02-28 21:56 UTC, Vitaliy-Kalenichenko commented on backend/package.json
> +        "@fastify/deepmerge": "1.3.0",
Couldn't find where this package has been used

2024-02-28 22:00 UTC, Vitaliy-Kalenichenko commented on backend/src/common/files/file.service.ts
> +    public find(): ReturnType<IService['find']> {
Check it there is a way to get rid of 'empty' methods

2024-02-28 22:02 UTC, Vitaliy-Kalenichenko requested changes
Check linters

2024-03-01 17:13 UTC, closed without merging