rg-40: Add Ability Edit Template
BinaryStudioAcademy/bsa-winter-2023-2024-resumegemm pull request #57
Opened 2024-02-21 22:52 UTC by siefimov

2024-02-22 09:11 UTC, Vitaliy-Kalenichenko commented
Resolve conflicts

2024-02-22 16:58 UTC, siefimov commented
Conflicts resolved.

2024-02-23 09:14 UTC, Vitaliy-Kalenichenko approved these changes

2024-02-25 18:44 UTC, apofis96 requested changes

2024-02-25 18:44 UTC, apofis96 commented on frontend/src/bundles/edit-temlate/types/types.ts
> +} from '../../../../../shared/build/bundles/templates/templates.js';
Don't use relative path for shared

2024-02-25 22:08 UTC, Vitaliy-Kalenichenko commented
Conflicts :(

2024-02-25 22:47 UTC, siefimov commented on frontend/src/bundles/edit-temlate/types/types.ts
> +} from '../../../../../shared/build/bundles/templates/templates.js';
Fixed.

2024-02-25 22:51 UTC, merged