rg-4: Add Common Inputs
BinaryStudioAcademy/bsa-winter-2023-2024-resumegemm pull request #6
Opened 2024-02-12 09:05 UTC by Valentyn13

2024-02-12 11:01 UTC, Valentyn13 commented
I have hardcoded width of the input and text-area in the styles, it will be necessary to remove this and replace it with some dynamic value. If adding width props to the components  is the right solution?

2024-02-12 18:49 UTC, apofis96 approved these changes

2024-02-12 21:44 UTC, Vitaliy-Kalenichenko commented on frontend/src/bundles/common/components/input/input.tsx
>      const { field } = useFormController({ name, control });
This component should not know anything about the outer scope

2024-02-12 21:45 UTC, Vitaliy-Kalenichenko commented on frontend/src/bundles/common/components/input/input.tsx
> +            <input
I'd like to have BaseInput component, and FormGroup component with validation, label, etc...

2024-02-12 21:46 UTC, Vitaliy-Kalenichenko commented on frontend/src/bundles/common/components/input/input.tsx
> +                ${!hasError && field.value.length > 0 && styles.filled}
Avoid such conditions in layout

2024-02-12 21:46 UTC, Vitaliy-Kalenichenko commented on frontend/src/bundles/common/components/text-area/text-area.tsx
> +            ${!hasError && field.value.length > 0 && styles.filled}
Looks like copy-paste

2024-02-12 21:47 UTC, Vitaliy-Kalenichenko commented on frontend/src/bundles/common/components/input/input.tsx
> +                <span className={styles.errorText}>{error as string}</span>
Avoid using `as` operator

2024-02-12 21:47 UTC, Vitaliy-Kalenichenko commented on frontend/src/bundles/common/components/input/styles.module.scss
> +    width: 280px;
Why `width` is fixed?

2024-02-12 21:48 UTC, Vitaliy-Kalenichenko commented on frontend/src/bundles/common/components/input/styles.module.scss
> +    position: absolute;
Try to find better solution, without `position: absolute;`

2024-02-12 21:50 UTC, Vitaliy-Kalenichenko requested changes
TextArea component looks like copy-paste of Input component. This is considered bad practice

2024-02-14 07:57 UTC, Valentyn13 commented
![usage of inputs](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-resumegemm/assets/91594923/c5a51ef2-85cb-4f9c-89e0-a3d18b90e355)

2024-02-14 20:40 UTC, Vitaliy-Kalenichenko commented
Looks great
Resolve conflicts

2024-02-15 08:54 UTC, Vitaliy-Kalenichenko commented on .github/CODEOWNERS
Why this file has been removed?

2024-02-15 08:54 UTC, Vitaliy-Kalenichenko commented on .gitignore
> -.idea
It would be nice to have it here

2024-02-15 17:46 UTC, closed without merging