rg-18: Add dropdown
BinaryStudioAcademy/bsa-winter-2023-2024-resumegemm pull request #8
Opened 2024-02-12 12:35 UTC by vlad-blip

Some values are hardcoded, they are going to be changed in the future to common variables. Icon isn't present here yet, waiting for fontawesome pull request.

2024-02-12 18:48 UTC, apofis96 approved these changes

2024-02-12 21:58 UTC, Vitaliy-Kalenichenko commented on frontend/src/bundles/common/components/dropdown/dropdown.tsx
> +    const { field } = useFormController({
This component knows too much about the environment it assumed to be used. Avoid using `react-hook-form` and similar packages inside the component

2024-02-12 21:59 UTC, Vitaliy-Kalenichenko requested changes
A good attempt to create your own dropdown, but it is better to use ready-made solutions that can be customized to fit the existing application design

2024-02-12 22:00 UTC, Vitaliy-Kalenichenko commented on frontend/src/bundles/common/components/dropdown/dropdown.tsx
> +                className={`${styles.dropdown}  ${active ? styles.active : ''}`}
It's better to use some packages like `calssnames` or `clsx` instead of string interpolation

2024-02-12 22:02 UTC, Vitaliy-Kalenichenko commented on frontend/src/bundles/common/components/dropdown/option/option.tsx
> +    onClick: ({ value, label }: { value: string; label: string }) => void;
It'd better to create a Type to type such props

2024-02-14 20:29 UTC, Vitaliy-Kalenichenko approved these changes

2024-02-14 20:30 UTC, Vitaliy-Kalenichenko commented
Resolve conflicts

2024-02-15 17:08 UTC, merged