Task/rg 62 user email confirmation
BinaryStudioAcademy/bsa-winter-2023-2024-resumegemm pull request #80
Opened 2024-02-27 12:30 UTC by MariaPetrukhnova

Add main logic:
1. Submit sign up data
2. Get it on back and check, send verification email
3. Create email confirmation via emailService
4. Confirm email with click on link in email
5. Accept token on confirmed-email route
6. Add to database new user with sign up data and emailConfirmed: true for further restriction in login

I know can have a lot of change request because there are a lot to do further: redirestion, login proceeding. But I need here some comments from you, because it was rather challenging task for me with entry code in our project

![1](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-resumegemm/assets/110037119/5a58ac01-b5e2-466b-b77b-567517658706)
![2](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-resumegemm/assets/110037119/c5153a71-eef0-4088-8ad2-3174a77664f1)
![3](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-resumegemm/assets/110037119/408c6bf0-3453-45ff-9a9f-199bd476a4b8)
![4](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-resumegemm/assets/110037119/212b0c94-41ae-4c15-bcfe-eee78c0c31e9)
![5](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-resumegemm/assets/110037119/abd406db-7ee9-4985-9290-240498e47d27)

2024-02-28 21:51 UTC, Vitaliy-Kalenichenko commented
Conflicts :(

2024-02-29 21:29 UTC, Vitaliy-Kalenichenko commented
Conflicts :(

2024-03-06 08:46 UTC, MaxPoplavskiy requested changes

2024-03-06 08:46 UTC, MaxPoplavskiy commented on backend/src/bundles/auth/auth.controller.ts
> +interface JwtPayload {
Consider changing to a type

![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-resumegemm/assets/92567020/01d25ca6-7bfc-4ce8-aa64-53e92a24ba5e)

2024-03-06 08:46 UTC, MaxPoplavskiy commented on backend/src/bundles/auth/auth.controller.ts
> +                payload: { message: 'Email confirmed successfully' },
Consider moving to separate email messages enum

2024-03-06 08:46 UTC, MaxPoplavskiy commented on backend/src/bundles/auth/auth.service.ts
> +        // eslint-disable-next-line @typescript-eslint/no-floating-promises
Consider refactoring without disabling rules

2024-03-06 08:46 UTC, MaxPoplavskiy commented on backend/src/bundles/auth/auth.service.ts
> +            text: 'You have successfully registred on ResumeGemm',
Consider moving to enum

2024-03-06 08:46 UTC, MaxPoplavskiy commented on backend/src/bundles/users/user.service.ts
> +interface JwtPayload {
Repeats in auth.controller, consider moving to a separate file

2024-03-06 08:46 UTC, MaxPoplavskiy commented on frontend/src/bundles/auth/components/comfirmed-email-page/confirmed-email-page.tsx
> +    const [counter, setCounter] = useState(15);
Move 15 to a constant

2024-03-06 08:46 UTC, MaxPoplavskiy commented on frontend/src/bundles/auth/components/comfirmed-email-page/confirmed-email-page.tsx
> +        }, 1000);
Move to a constant

2024-03-06 08:46 UTC, MaxPoplavskiy commented on frontend/src/bundles/auth/components/sign-up-form/components/styles.module.scss
> +    background: #ebeff1;
consider replacing with css vars

2024-03-06 08:46 UTC, MaxPoplavskiy commented on frontend/src/bundles/auth/components/sign-up-form/constants/constants.ts
> +    // emailConfirmed: false
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-resumegemm/assets/92567020/ca23f01c-249c-43b1-a488-0d85ef3435b5)

2024-03-06 08:46 UTC, MaxPoplavskiy commented on frontend/src/bundles/auth/components/sign-up-form/sign-up-form.tsx
> +                'Thank you for sign up! Check please your email to confirm registration',
consider moving to enum

2024-03-06 08:46 UTC, MaxPoplavskiy commented on frontend/src/bundles/auth/components/sign-up-form/validation/sign-up-validation.ts
> +    // emailConfirmed: boolean;
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-resumegemm/assets/92567020/24d355cd-f3bc-4933-94b3-405a2092c0f6)

2024-03-06 08:46 UTC, MaxPoplavskiy commented on frontend/src/bundles/auth/components/sign-up-form/validation/sign-up-validation.ts
> +    // emailConfirmed: joi.boolean()
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-resumegemm/assets/92567020/b5a3fd8b-00ed-4143-9548-78beeb66b43f)

2024-03-06 08:46 UTC, MaxPoplavskiy commented on frontend/src/bundles/payment/pages/subscription-payment.tsx
> +    // eslint-disable-next-line @typescript-eslint/no-unused-vars
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-resumegemm/assets/92567020/77e8d10a-4f40-4f71-9307-53d24e00639c)

2024-03-06 08:46 UTC, MaxPoplavskiy commented on frontend/src/bundles/users/users-api.ts
> +        setTimeout(() => false, 5000);
consider moving to a constant

2024-03-06 08:46 UTC, MaxPoplavskiy commented on frontend/src/framework/storage/enums/storage-key.enum.ts
> +    NAME_EXIST = 'nameExist',
consider using the same case

2024-03-06 09:20 UTC, MaxPoplavskiy commented on frontend/src/bundles/users/users-api.ts
> +        setTimeout(() => false, 5000);
Isn't this setTimeout redundant?

2024-03-07 07:18 UTC, MaxPoplavskiy requested changes

2024-03-07 07:18 UTC, MaxPoplavskiy commented on backend/src/bundles/auth/enums/message.enum.ts
> +    SUCCESSFULLY_REGISTRED: 'You have successfully registred on ResumeGemm',
Word misspelled(REGISTRED)

2024-03-07 07:18 UTC, MaxPoplavskiy commented on backend/src/bundles/auth/enums/message.enum.ts
> +const userMessages = {
rewrite as ts enum

2024-03-07 07:18 UTC, MaxPoplavskiy commented on backend/src/common/database/enums/database-column-name.enum.ts
> -    DESCRIPTION = 'description',
Wouldn't it crash our dev branch?

2024-03-07 07:18 UTC, MaxPoplavskiy commented on frontend/src/framework/api/http-api.ts
> +        // eslint-disable-next-line @typescript-eslint/no-throw-literal
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-resumegemm/assets/92567020/6719e84f-c9c2-491f-83d2-128657a505d3)

2024-03-07 07:18 UTC, MaxPoplavskiy commented on shared/src/bundles/users/types/user-sign-up-request-dto.type.ts
> +    confirm_password?: string;
consider using camelCase

2024-03-10 15:56 UTC, Icerock10 requested changes

2024-03-10 15:56 UTC, Icerock10 commented on backend/src/bundles/auth/auth.controller.ts
> +            const token = await this.authService.signUp(options.body);
are you sure this line returns only token?

2024-03-10 15:56 UTC, Icerock10 commented on backend/src/bundles/auth/auth.controller.ts
> +                        message: 'Email confirm token not found',
Write an exception message for this

2024-03-10 15:56 UTC, Icerock10 commented on backend/src/bundles/auth/helpers/get-template.ts
> +    context: object;
`context` contains certain fields

2024-03-10 15:56 UTC, Icerock10 commented on backend/src/bundles/users/user.repository.ts
> +    }
Maria wrote this method, however, it has 0 usage across the app, maybe remove it?

2024-03-10 15:56 UTC, Icerock10 commented on backend/src/bundles/users/user.service.ts
> +        return await this.userRepository.confirmEmail(id);
```suggestion
        return this.userRepository.confirmEmail(id);
```

2024-03-10 15:56 UTC, Icerock10 commented on frontend/src/bundles/auth/components/confirmed-email-page/confirmed-email-page.tsx
> +import { useCallback, useEffect, useState } from 'react';
```suggestion
import { useAppDispatch, useCallback, useEffect, useState } from '~/bundles/common/hooks/hooks';
```

2024-03-10 16:27 UTC, Icerock10 commented
As per the view, I would suggest to create a "Waiting page" like resume.io has, it's not a good ux to keep the user on the sign-up page, or we can let him register, and then ask to confirm email let's say in profile

![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-resumegemm/assets/24661681/ee6dabab-a999-4ae1-9be6-327a2b727da8)

2024-03-15 17:39 UTC, vlad-blip approved these changes

2024-03-15 17:40 UTC, vlad-blip commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add email confirmation](https://trello.com/c/UWw1OVVa/62-add-email-confirmation)

2024-03-18 11:17 UTC, Icerock10 approved these changes

2024-03-18 18:54 UTC, MaxPoplavskiy commented on backend/src/common/database/enums/database-column-name.enum.ts
> -    DESCRIPTION = 'description',
Wouldn't it crash our dev branch?

2024-03-18 19:01 UTC, MaxPoplavskiy commented
Wait for rg-180 to be merged

2024-03-20 13:19 UTC, MaxPoplavskiy approved these changes

2024-03-20 13:22 UTC, MaxPoplavskiy requested changes
Resolve old request changes

2024-03-20 13:22 UTC, MaxPoplavskiy commented on frontend/src/bundles/auth/components/sign-up-form/components/styles.module.scss
> +    background: #ebeff1;
consider replacing with css vars

2024-03-20 13:57 UTC, ValentinaTenus commented
> Resolve old request changes

they are resolved

2024-03-20 14:26 UTC, MaxPoplavskiy approved these changes

2024-03-20 14:27 UTC, merged