rg-87: Add oauth resign in
BinaryStudioAcademy/bsa-winter-2023-2024-resumegemm pull request #90
Opened 2024-02-28 22:35 UTC by Icerock10

2024-02-29 22:07 UTC, Icerock10 commented
The basic auth client logic will be refactored in the next PR.

2024-02-29 22:25 UTC, Vitaliy-Kalenichenko commented on backend/src/bundles/auth/auth.controller.ts
> +            const userWithProfileRelation = oauthId
It's better to have two methods instead of this condition

2024-02-29 22:34 UTC, Vitaliy-Kalenichenko requested changes

2024-02-29 22:34 UTC, Vitaliy-Kalenichenko commented on frontend/src/bundles/common/components/free-access-route/free-access-route.tsx
If you decided to replace `NoAuthRoute` component, the update `PrivateRoute` component as well

2024-03-01 01:38 UTC, Icerock10 commented on frontend/src/bundles/common/components/free-access-route/free-access-route.tsx
https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-resumegemm/pull/107

2024-03-02 22:08 UTC, closed without merging

2024-03-02 22:09 UTC, Icerock10 commented
closed, as merged into https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-resumegemm/tree/task/rg-75-add-oauth-disconnect